package com.entity;

import java.util.Date;

public class DealCategory extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.url_name
     *
     * @mbg.generated
     */
    private String urlName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.publish_status
     *
     * @mbg.generated
     */
    private Integer publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.order_num
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_category.deep
     *
     * @mbg.generated
     */
    private Integer deep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.parent_id
     *
     * @return the value of deal_category.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.parent_id
     *
     * @param parentId the value for deal_category.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.name
     *
     * @return the value of deal_category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.name
     *
     * @param name the value for deal_category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.url_name
     *
     * @return the value of deal_category.url_name
     *
     * @mbg.generated
     */
    public String getUrlName() {
        return urlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.url_name
     *
     * @param urlName the value for deal_category.url_name
     *
     * @mbg.generated
     */
    public void setUrlName(String urlName) {
        this.urlName = urlName == null ? null : urlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.publish_status
     *
     * @return the value of deal_category.publish_status
     *
     * @mbg.generated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.publish_status
     *
     * @param publishStatus the value for deal_category.publish_status
     *
     * @mbg.generated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.create_time
     *
     * @return the value of deal_category.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.create_time
     *
     * @param createTime the value for deal_category.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.order_num
     *
     * @return the value of deal_category.order_num
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.order_num
     *
     * @param orderNum the value for deal_category.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_category.deep
     *
     * @return the value of deal_category.deep
     *
     * @mbg.generated
     */
    public Integer getDeep() {
        return deep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_category.deep
     *
     * @param deep the value for deal_category.deep
     *
     * @mbg.generated
     */
    public void setDeep(Integer deep) {
        this.deep = deep;
    }
}