package com.entity;

public class DealDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_detail.deal_id
     *
     * @mbg.generated
     */
    private Integer dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal_detail.deal_detail
     *
     * @mbg.generated
     */
    private String dealDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_detail.deal_id
     *
     * @return the value of deal_detail.deal_id
     *
     * @mbg.generated
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_detail.deal_id
     *
     * @param dealId the value for deal_detail.deal_id
     *
     * @mbg.generated
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal_detail.deal_detail
     *
     * @return the value of deal_detail.deal_detail
     *
     * @mbg.generated
     */
    public String getDealDetail() {
        return dealDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal_detail.deal_detail
     *
     * @param dealDetail the value for deal_detail.deal_detail
     *
     * @mbg.generated
     */
    public void setDealDetail(String dealDetail) {
        this.dealDetail = dealDetail == null ? null : dealDetail.trim();
    }
}