package com.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Deal extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.sku_id
     *
     * @mbg.generated
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_class
     *
     * @mbg.generated
     */
    private Byte dealClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.merchantSku
     *
     * @mbg.generated
     */
    private Integer merchantsku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_title
     *
     * @mbg.generated
     */
    private String dealTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_price
     *
     * @mbg.generated
     */
    private BigDecimal dealPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.merchant_price
     *
     * @mbg.generated
     */
    private BigDecimal merchantPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.settlement_price_max
     *
     * @mbg.generated
     */
    private BigDecimal settlementPriceMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.settlement_price
     *
     * @mbg.generated
     */
    private BigDecimal settlementPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.discount
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.bonus_points
     *
     * @mbg.generated
     */
    private Integer bonusPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_type
     *
     * @mbg.generated
     */
    private Integer dealType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.image_id
     *
     * @mbg.generated
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.image_gen_path
     *
     * @mbg.generated
     */
    private String imageGenPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_level
     *
     * @mbg.generated
     */
    private Integer dealLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.max_purchase_count
     *
     * @mbg.generated
     */
    private Integer maxPurchaseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.publish_status
     *
     * @mbg.generated
     */
    private Integer publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.inventory_amount
     *
     * @mbg.generated
     */
    private Integer inventoryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.vendibility_amount
     *
     * @mbg.generated
     */
    private Integer vendibilityAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.oos_status
     *
     * @mbg.generated
     */
    private Integer oosStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.publish_time
     *
     * @mbg.generated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_detail
     *
     * @mbg.generated
     */
    private String dealDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.down_shelf
     *
     * @mbg.generated
     */
    private Integer downShelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.area_id
     *
     * @return the value of deal.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.area_id
     *
     * @param areaId the value for deal.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.area_name
     *
     * @return the value of deal.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.area_name
     *
     * @param areaName the value for deal.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.sku_id
     *
     * @return the value of deal.sku_id
     *
     * @mbg.generated
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.sku_id
     *
     * @param skuId the value for deal.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_class
     *
     * @return the value of deal.deal_class
     *
     * @mbg.generated
     */
    public Byte getDealClass() {
        return dealClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_class
     *
     * @param dealClass the value for deal.deal_class
     *
     * @mbg.generated
     */
    public void setDealClass(Byte dealClass) {
        this.dealClass = dealClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.merchant_id
     *
     * @return the value of deal.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.merchant_id
     *
     * @param merchantId the value for deal.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.merchantSku
     *
     * @return the value of deal.merchantSku
     *
     * @mbg.generated
     */
    public Integer getMerchantsku() {
        return merchantsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.merchantSku
     *
     * @param merchantsku the value for deal.merchantSku
     *
     * @mbg.generated
     */
    public void setMerchantsku(Integer merchantsku) {
        this.merchantsku = merchantsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_title
     *
     * @return the value of deal.deal_title
     *
     * @mbg.generated
     */
    public String getDealTitle() {
        return dealTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_title
     *
     * @param dealTitle the value for deal.deal_title
     *
     * @mbg.generated
     */
    public void setDealTitle(String dealTitle) {
        this.dealTitle = dealTitle == null ? null : dealTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_price
     *
     * @return the value of deal.deal_price
     *
     * @mbg.generated
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_price
     *
     * @param dealPrice the value for deal.deal_price
     *
     * @mbg.generated
     */
    public void setDealPrice(BigDecimal dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.merchant_price
     *
     * @return the value of deal.merchant_price
     *
     * @mbg.generated
     */
    public BigDecimal getMerchantPrice() {
        return merchantPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.merchant_price
     *
     * @param merchantPrice the value for deal.merchant_price
     *
     * @mbg.generated
     */
    public void setMerchantPrice(BigDecimal merchantPrice) {
        this.merchantPrice = merchantPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.market_price
     *
     * @return the value of deal.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.market_price
     *
     * @param marketPrice the value for deal.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.settlement_price_max
     *
     * @return the value of deal.settlement_price_max
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementPriceMax() {
        return settlementPriceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.settlement_price_max
     *
     * @param settlementPriceMax the value for deal.settlement_price_max
     *
     * @mbg.generated
     */
    public void setSettlementPriceMax(BigDecimal settlementPriceMax) {
        this.settlementPriceMax = settlementPriceMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.settlement_price
     *
     * @return the value of deal.settlement_price
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.settlement_price
     *
     * @param settlementPrice the value for deal.settlement_price
     *
     * @mbg.generated
     */
    public void setSettlementPrice(BigDecimal settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.discount
     *
     * @return the value of deal.discount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.discount
     *
     * @param discount the value for deal.discount
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.bonus_points
     *
     * @return the value of deal.bonus_points
     *
     * @mbg.generated
     */
    public Integer getBonusPoints() {
        return bonusPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.bonus_points
     *
     * @param bonusPoints the value for deal.bonus_points
     *
     * @mbg.generated
     */
    public void setBonusPoints(Integer bonusPoints) {
        this.bonusPoints = bonusPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_type
     *
     * @return the value of deal.deal_type
     *
     * @mbg.generated
     */
    public Integer getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_type
     *
     * @param dealType the value for deal.deal_type
     *
     * @mbg.generated
     */
    public void setDealType(Integer dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.image_id
     *
     * @return the value of deal.image_id
     *
     * @mbg.generated
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.image_id
     *
     * @param imageId the value for deal.image_id
     *
     * @mbg.generated
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.image_gen_path
     *
     * @return the value of deal.image_gen_path
     *
     * @mbg.generated
     */
    public String getImageGenPath() {
        return imageGenPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.image_gen_path
     *
     * @param imageGenPath the value for deal.image_gen_path
     *
     * @mbg.generated
     */
    public void setImageGenPath(String imageGenPath) {
        this.imageGenPath = imageGenPath == null ? null : imageGenPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_level
     *
     * @return the value of deal.deal_level
     *
     * @mbg.generated
     */
    public Integer getDealLevel() {
        return dealLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_level
     *
     * @param dealLevel the value for deal.deal_level
     *
     * @mbg.generated
     */
    public void setDealLevel(Integer dealLevel) {
        this.dealLevel = dealLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.max_purchase_count
     *
     * @return the value of deal.max_purchase_count
     *
     * @mbg.generated
     */
    public Integer getMaxPurchaseCount() {
        return maxPurchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.max_purchase_count
     *
     * @param maxPurchaseCount the value for deal.max_purchase_count
     *
     * @mbg.generated
     */
    public void setMaxPurchaseCount(Integer maxPurchaseCount) {
        this.maxPurchaseCount = maxPurchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.publish_status
     *
     * @return the value of deal.publish_status
     *
     * @mbg.generated
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.publish_status
     *
     * @param publishStatus the value for deal.publish_status
     *
     * @mbg.generated
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.inventory_amount
     *
     * @return the value of deal.inventory_amount
     *
     * @mbg.generated
     */
    public Integer getInventoryAmount() {
        return inventoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.inventory_amount
     *
     * @param inventoryAmount the value for deal.inventory_amount
     *
     * @mbg.generated
     */
    public void setInventoryAmount(Integer inventoryAmount) {
        this.inventoryAmount = inventoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.vendibility_amount
     *
     * @return the value of deal.vendibility_amount
     *
     * @mbg.generated
     */
    public Integer getVendibilityAmount() {
        return vendibilityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.vendibility_amount
     *
     * @param vendibilityAmount the value for deal.vendibility_amount
     *
     * @mbg.generated
     */
    public void setVendibilityAmount(Integer vendibilityAmount) {
        this.vendibilityAmount = vendibilityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.oos_status
     *
     * @return the value of deal.oos_status
     *
     * @mbg.generated
     */
    public Integer getOosStatus() {
        return oosStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.oos_status
     *
     * @param oosStatus the value for deal.oos_status
     *
     * @mbg.generated
     */
    public void setOosStatus(Integer oosStatus) {
        this.oosStatus = oosStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.start_time
     *
     * @return the value of deal.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.start_time
     *
     * @param startTime the value for deal.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.end_time
     *
     * @return the value of deal.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.end_time
     *
     * @param endTime the value for deal.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.publish_time
     *
     * @return the value of deal.publish_time
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.publish_time
     *
     * @param publishTime the value for deal.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.merchant_code
     *
     * @return the value of deal.merchant_code
     *
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.merchant_code
     *
     * @param merchantCode the value for deal.merchant_code
     *
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.create_time
     *
     * @return the value of deal.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.create_time
     *
     * @param createTime the value for deal.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.update_time
     *
     * @return the value of deal.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.update_time
     *
     * @param updateTime the value for deal.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_detail
     *
     * @return the value of deal.deal_detail
     *
     * @mbg.generated
     */
    public String getDealDetail() {
        return dealDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_detail
     *
     * @param dealDetail the value for deal.deal_detail
     *
     * @mbg.generated
     */
    public void setDealDetail(String dealDetail) {
        this.dealDetail = dealDetail == null ? null : dealDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.down_shelf
     *
     * @return the value of deal.down_shelf
     *
     * @mbg.generated
     */
    public Integer getDownShelf() {
        return downShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.down_shelf
     *
     * @param downShelf the value for deal.down_shelf
     *
     * @mbg.generated
     */
    public void setDownShelf(Integer downShelf) {
        this.downShelf = downShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.category_id
     *
     * @return the value of deal.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.category_id
     *
     * @param categoryId the value for deal.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}