package com.common.orm.mapper;

import com.entity.DealCategory;

public interface DealCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    int insert(DealCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    int insertSelective(DealCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    DealCategory selectByPrimaryKey(Integer parentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DealCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DealCategory record);
}