package com.common.orm.mapper;

import com.entity.Deal;

public interface DealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insert(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insertSelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    Deal selectByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deal record);
}