package com.common.orm.mapper;

import com.entity.DealDetail;

public interface DealDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    int insert(DealDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    int insertSelective(DealDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    DealDetail selectByPrimaryKey(Integer dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DealDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DealDetail record);
}